Vagrant.configure("2") do |config|
  config.vm.box = "tknerr/managed-server-dummy"
  config.vm.synced_folder '.', '/home/ricardog/src/cr-gdal', disabled: true
  
  config.vm.provider :managed do |managed, override|
    managed.server = "192.168.0.46"
    override.ssh.username = 'ricardog'
    override.ssh.private_key_path = '/Users/ricardog/.ssh/id_rsa'
  end
end
